### ISSUE TITLE
Doc Missing Instructions on How to Close App

### ISSUE THREAD

**Issue by sandmanmax** [sensel/morph-docs#11]
In Windows 10, the App has no title bar, no right click context menu, no menu icons, no close icon - nothing.  And the documentation has no instruction for how to close the thing.  I basically had to just hit keys that other software commonly used (Alt-F4 works) or force close the app through Windows.

**Comment by AlexSensel** [comment]
Thank you for the App feedback. You can also quit the app using Control+Q on Windows and we will add this to the guide. We will also add the title bar and an exit button for future releases.
