### ISSUE TITLE
Documentation Should Cover Applicable Software Version Requirements

### ISSUE THREAD

**Issue by sandmanmax** [sensel/morph-docs#12]
From what I'm gleaning from the Support forum, the Art Overlay was implemented using technology that only works with the latest version of some of the common graphics programs.  This was never mentioned anywhere and now my Morph is virtually useless unless I upgrade all my software.  You need to cover this in the documentation.

**Comment by AlexSensel** [comment]
Thank you for the feedback. We will make sure to add versions to our documentation.
