### ISSUE TITLE
Frame Data Content Bitmask doc error

### ISSUE THREAD

**Issue by jarmitage** [sensel/morph-docs#13]
https://github.com/sensel/morph-docs/blob/master/docs/api.md#content-bitmask

> The Content Bitmask is used to enable or disable reporting of the five (5) parameters in Frame Data: Force Array, Labels Array, Accelerometer Data, Lost Frame Count. Set the byte value according to the parameters needed. For example, a value of “12” (01100) would report Labels Array and Accelerometer Data.

4 params, or 5 params?

**Comment by AlexSensel** [comment]
Thank you for reporting the issue. We forgot to add Contacts to that list.

**Comment by nyboer** [comment]
fixed.
