### ISSUE TITLE
Windows support for bluetooth should mention that a Win32 wrapper is available

### ISSUE THREAD

**Issue by nosuchtim** [sensel/morph-docs#2]
The statement "This support, however, is limited to applications that use the native windows API for MIDI" is not totally true - you should very briefly mention that there is a Win32 API wrapper for older desktop applications.  It's described in the same link you provided.  It's only appropriate and usable for developers, at the moment.

**Comment by nyboer** [comment]
Something like "This support, however, is limited to applications that use the UWP MIDI API (or the Win32 wrapper for UWP MIDI)." ?

**Comment by nyboer** [comment]
fixed and commited.
