### ISSUE TITLE
Documentation should mention how to mount the Morph

### ISSUE THREAD

**Issue by anlumo** [sensel/morph-docs#3]
I'd like to mount the Morph on something like a microphone/camera stand (1/4" screw). Since music seems to be a major use case for the device, it might be interesting to make some suggestions on how to do that in the documentation.

**Comment by nyboer** [comment]
thanks for the feedback. I think this will be a great topic for the (coming-soon) forums, since there are a lot of solutions (including mic stand attachments for iPads) that people will no doubt have opinions on.
