### ISSUE TITLE
Please add more information about scan framerate and possible baudrates

### ISSUE THREAD

**Issue by nesdnuma** [sensel/morph-docs#5]
Hello,

Basic information about the Morph states that there is a high-tresolution mode and a high-speed mode. Please add more information about how to either switch from one mode to the other.

Moreover, if the scanrate can be set freely, what is the authorized value range? 

Also, what are the authorized baudrates for communications between the Morph and an Arduino. I have tried to go beyond 115200 bauds but it doesn't seem to function.

More examples would be welcome. By the way, no one from Sensel seem to check the official forum and answer the messages there.

Thank you in advance.

**Comment by azarraga** [comment]
Hi nesdnuma, thanks for the message. The team here is working to add more detail to the Morph guide about the various scan modes we support. In general, you can use SenselSetScanDetail() in the new API to change the sensor scan resolution. There are three supported modes (High Detail (0), Medium Detail (1), Low Detail (2)). The medium detail is the default mode. High detail gives you finer spatial resolution, but lower speed. The low detail mode gives you a faster framerate but lower spatial resolution. I'll add more detail on this in the documentation shortly.

By default, the sensor scans as fast as possible when you're communicating with it through the API. Therefore, the actual framerate depends on which detail/resolution mode you have set (typically between 80 and 1000Hz). Setting the framerate sets the maximum allowed scanning framerate, which is useful if your application is reading from the sensor significantly slower than the sensor is scanning (in an Arduino use-case for instance). The maximum allowable framerate value is 2000 (value is in Hz).

Baudrate is set to 115200 for the Morph hacker cable, so you can't go below or above this value.

Apologies on the forum no-reply! The team here wasn't getting notifications from the forum but we're working to rectify this asap.

**Comment by jarmitage** [comment]
@azarraga your documentation about this and your statement above are quite confusing. You seem to be simultaneously saying that the max scan rate is 1kHz and 2kHz.

Is there a way to actually receive data at 2kHz or not? If not, why do you mention 2kHz scan rate at all?

**Comment by AlexSensel** [comment]
Hello, we understand the confusion and will try to clarify it here and in the documentation. There are two forms of maximum frame rate: allowable and actual. 

The allowable maximum frame rate is the highest you can set the frame rate value to in the API, this value is 2000.

The actual maximum frame rate is limited by the scanning speed of the Sensel Device. Currently, the fastest actual maximum frame rate is around 1000 frames per second, when in low detail mode and using buffering on the Sensel Morph.

The allowable maximum frame rate acts as a limiter to the actual maximum frame rate, so if you set the allowable frame rate to 100, then the actual frame rate will be 100. If you set the allowable frame rate beyond 1000, the Sensel Device will attempt to scan as fast as possible, which will result in the fastest possible allowable frame rate given the parameters for scanning.

**Comment by jarmitage** [comment]
So it is not possible to get a frame rate of 2kHz?

**Comment by AlexSensel** [comment]
It is currently not possible to get a frame rate of 2kHz from the Sensel Morph. We kept our API flexible to allow for faster scanning if the Sensel Device supports it, but the Sensel Morph can currently scan around 1kHz max.
