### ISSUE TITLE
linux driver support

### ISSUE THREAD

**Issue by hareshel** [sensel/morph-docs#7]
Do you have linux driver for this sensel device? 

If not, let me know how to read the data from sensel device. I mean USB packet frame and response.

**Comment by AlexSensel** [comment]
Thank you for reaching out. There are a few possible responses to this question. Hopefully one of these answers it:
1) If you are looking for serial contact or force frame data, you can use our Sensel API, that gives you access to our C API along with compiled binary installers for Windows, Mac and Linux. https://github.com/sensel/sensel-api along with a guide primer here: http://guide.sensel.com/api/
2) When not communicating over serial and Overlays are placed on the Morph, the device can act as a HID or USB device that sends standard keyboard, mouse, MIDI and digitizer events. A driver is not needed, except for:
3) Digitizer USB (Art Overlay and No Overlay Painting Mode) does require a driver on Mac and we have experienced some variation in support on Linux. We plan to add greater support for Linux digitizer in the future.

**Comment by hareshel** [comment]
I am interested in point 2. How to do I ensure overlays are in Morph. When I connected to PC, it is enumerated as HID-MUltitouch, input. But no response on mouse pointer on PC desktop.

**Comment by AlexSensel** [comment]
If you have an Overlay, simply place it on the device and it will send over HID/USB events. If you are using an Art Overlay, you will need to update the firmware to 0.9 using the Sensel App. If you do not have an Overlay, you can activate the Sensel Morph as a touchpad by using the SenselApp. 

We currently do not have a version of the App for Linux but will be releasing one in the future. If you have access to the a Windows or Mac computer, download the latest App (currently 0.9), update the Morph firmware, and then go to the No Overlay mode. Here, you can select how the Morph behaves with no Overlay on the device. Then press "Send To Morph" to send this change to the Morph.

Hope this helps!

**Comment by hareshel** [comment]
Is there a way to configure this device as touch screen rather than touch pad when no overlay mode is choosen? It is detected as USB HID device. But sends REL_X values. need of ABS_X value

**Comment by AlexSensel** [comment]
The Painting Mode under the No Overlay dropdown menu sends absolute values instead of relative values. I hope this helps.

**Comment by hareshel** [comment]
I tried that it doesn't send abs value. Can you please confirm?

**Comment by AlexSensel** [comment]
Is it still acting as a Trackpad with no Overlay on? If so, did you press the "Send Map to Morph" button after selecting the "Painting Mode" option? Painting Mode should act as a HID digitizer. If this does not work, please send us some details about your OS and computer so we can attempt to recreate the error. Thank you.

**Comment by hareshel** [comment]
Painting mode doesn't give the abs coordinates. But sensel library could
able to give me the coordinates. Is there any way to change the xres and
yres coordinates? Means of orientation?. TO put it in another manner, Is
there way to change to x,y(0,0) to another corner in the sensel device.?

**Comment by hareshel** [comment]
What is the resolution of morph ? I mean xres and y res ie (600x700) or ?Is
there any way to change the xres and yres coordinates? Means of
orientation?. TO put it in another manner, Is there way to change to
x,y(0,0) to another corner in the sensel device.?
