### ISSUE TITLE
Won't update on Windows 7

### ISSUE THREAD

**Issue by ampersandra** [sensel/morph-docs#8]
I've downloaded and installed the driver for Windows 7/8, and the program _will_ start, but as soon as I go to the Settings page to try and update the Morph, the pop-up for "restarting" that it does on Windows 7 when you go to a new page on the app just keeps popping up over and over again, very quickly and it won't let me update the Morph. How can I fix this or make it useable?

**Comment by AlexSensel** [comment]
Hello, thank you for reaching out and sorry for the issue. We just released a new version of the Sensel App today (0.10.6) that may solve your issue. Please go to sensel.com/start to download the latest version. If you continue to have issues, please let us know.

**Comment by ampersandra** [comment]
Thank you, I've gotten it to work!
